# Generated by Django 5.1.6 on 2025-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emp_deg', models.CharField(max_length=50)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
